pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r calculator-app/requirements.txt'
            }
        }

        stage('Build') {
            steps {
                sh 'python3 -m py_compile calculator-app/calculator.py'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest calculator-app/test_calculator.py --junitxml=test-results/results.xml'
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'test-results/results.xml'
            }
        }
    }

    post {
        success {
            echo "Pipeline Succeeded!"
        }
        failure {
            echo "Pipeline Failed!"
        }
    }
}
