pipeline {
    agent any

    environment {
        VENV = "venv"
    }

    stages {

        stage('Create Virtual Environment') {
            steps {
                sh 'python3 -m venv ${VENV}'
                sh './${VENV}/bin/pip install --upgrade pip'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh './${VENV}/bin/pip install -r calculator-app/requirements.txt'
            }
        }

        stage('Build') {
            steps {
                sh './${VENV}/bin/python -m py_compile calculator-app/calculator.py'
            }
        }

        stage('Run Tests') {
            steps {
                sh './${VENV}/bin/pytest calculator-app/test_calculator.py --junitxml=test-results/results.xml'
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'test-results/results.xml'
            }
        }
    }

    post {
        success {
            echo "Pipeline Succeeded!"
        }
        failure {
            echo "Pipeline Failed!"
        }
    }
}
