pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run App Build Script') {
            steps {
                sh 'bash build.sh'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'bash test.sh'
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'test-results/*.xml'
            }
        }
    }

    post {
        failure {
            echo 'Pipeline Failed!'
        }
        success {
            echo 'Pipeline Succeeded!'
        }
    }
}
